test: test_summation pad test_parity

test_summation:
	@echo "===== [Testing Summation Analysis] ========="
	python3 src/summation_analysis.py examples/sum.prog

test_parity:
	@echo "===== [Testing Parity Analysis] ============"
	python3 src/parity_analysis.py examples/parity.prog

pad:
	@echo "\n"
