test: test_summation test_parity

test_summation:
	@echo "===== [Testing Summation Analysis] ========="
	python3 src/summation_analysis.py examples/sum.prog
	@echo "\n"

test_parity:
	@echo "===== [Testing Parity Analysis] ============"
	python3 src/parity_analysis.py examples/parity.prog
